-- AlterTable
ALTER TABLE "BugEntry"
ADD COLUMN "branch" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customer" TEXT NOT NULL DEFAULT '';

ALTER TABLE "BugEntry" ALTER COLUMN "branch" DROP DEFAULT;
ALTER TABLE "BugEntry" ALTER COLUMN "customer" DROP DEFAULT;

-- AlterTable
ALTER TABLE "MiscEntry"
ADD COLUMN "branch" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customer" TEXT NOT NULL DEFAULT '';

ALTER TABLE "MiscEntry" ALTER COLUMN "branch" DROP DEFAULT;
ALTER TABLE "MiscEntry" ALTER COLUMN "customer" DROP DEFAULT;

-- AlterTable
ALTER TABLE "UIEntry"
ADD COLUMN "branch" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customer" TEXT NOT NULL DEFAULT '';

ALTER TABLE "UIEntry" ALTER COLUMN "branch" DROP DEFAULT;
ALTER TABLE "UIEntry" ALTER COLUMN "customer" DROP DEFAULT;
